BROKER: Delete School
Mums-Who-Code/SCMS.Services pull request #133
Opened 2021-11-14 05:14 UTC by muhammadmnorouzi

closes #110

2021-11-14 21:12 UTC, ShriHumrudha commented
Here we are now.

2021-11-15 05:04 UTC, ShriHumrudha requested changes

2021-11-15 05:04 UTC, ShriHumrudha commented on SCMS.Services.Api/Brokers/Storages/StorageBroker.School.cs
> +
Remove these extra lines.

2021-11-15 16:35 UTC, muhammadmnorouzi commented on SCMS.Services.Api/Brokers/Storages/StorageBroker.School.cs
> +
All are removed.

2021-11-16 01:54 UTC, ShriHumrudha approved these changes

2021-11-16 01:54 UTC, merged