BROKER: Delete Guardian
Mums-Who-Code/SCMS.Services pull request #137
Opened 2021-11-14 05:35 UTC by muhammadmnorouzi

closes #118

2021-11-17 20:26 UTC, ShriHumrudha requested changes

2021-11-17 20:26 UTC, ShriHumrudha commented on SCMS.Services.Api/Brokers/Storages/StorageBroker.Guardian.cs
> +
Run code cleanup.

2021-11-18 16:32 UTC, ShriHumrudha requested changes

2021-11-18 16:32 UTC, ShriHumrudha commented on SCMS.Services.Api/Brokers/Storages/StorageBroker.Guardian.cs
> +
Remove this extra line

2021-11-18 17:30 UTC, muhammadmnorouzi commented on SCMS.Services.Api/Brokers/Storages/StorageBroker.Guardian.cs
> +
Thank you for your time and reviews.

2021-11-18 20:31 UTC, ShriHumrudha approved these changes

2021-11-18 20:31 UTC, merged